// _package-react-navigation/src/Navigation.jsx
import React from 'react';

export default ({ title, name, links }) => 
  <div>
    <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
      <div className="navbar-brand" to="/">
        {title}
      </div>
      <div className="float-right text-right" >
        { links && links.map((l, i) => {
            return <a className="pr-4" key={i} href={l.url}>{l.name}</a>
        }) }
      </div>
    </nav>
    <div className="bg-secondary p-2">
      { name !== undefined ? `Logged in: ${name}` : 'Not logged in.'}
    </div>
  </div>

// _package-angular-navigation/projects/navigation/src/lib/navigation.component.ts
import { Component, Input } from "@angular/core";
import { Link } from "./navigation.link.model";

@Component({
  selector: "dfe-navigation",
  template: `
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <span class="navbar-brand" >
          {{ title }}
      </span>
      <div class="float-right text-right" >
          <a *ngFor="let link of links" class="pr-4" href="{{link.url}}">{{link.name}}</a>
      </div>
    </nav>
    <div class="bg-secondary p-2">
        {{ subtext }}
    </div>`
})
export class NavigationComponent {
  @Input() title: string;
  @Input() subtext: string;
  @Input() links: Link[];
}
